// @ts-check
import { defineConfig } from 'astro/config';

// Production host: Firebase Hosting (site `themonkeyvault` in project
// tmv-management), deployed by the TMV-Members repo's `hosting:web` target
// (scripts/build-web.sh assembles this dist/ + the /account and /waiver
// surfaces). Staging URL: https://themonkeyvault.web.app; the custom domain
// themonkeyvault.com attaches at DNS cutover — `site` already points there so
// canonicals/OG/sitemap are correct from day one (and staging pages canonical
// to the real domain instead of getting indexed).
//
// No `base`: the site serves from the domain root. (The old GitHub Pages
// deploy needed base '/TMV-Web'; Pages is retired — clean break.)
// Sitemap is generated by src/pages/sitemap.xml.ts (no external integration).
export default defineConfig({
  site: 'https://themonkeyvault.com',
  trailingSlash: 'ignore',
  build: { format: 'directory' },
  // Dev-only overlay (never ships in `astro build`/production) — off because
  // it sits over the phone-width preview during mobile work.
  devToolbar: { enabled: false },
  // Real routes (see CLAUDE.md — no device fork, no hash router) mean every
  // nav tap is a genuine navigation, unlike the old /m/ app's single-document
  // hash router, which never re-fetched anything after first load. 'hover' is
  // a safe, standard default for every link site-wide (only fires on real
  // intent). The bottom tab bar's own links go further — see the
  // data-astro-prefetch="viewport" override on them in MobileTabBar.astro.
  prefetch: { defaultStrategy: 'hover' },
});
