// @ts-check
import { defineConfig } from 'astro/config';

// Production host: Firebase Hosting (site `themonkeyvault` in project
// tmv-management), deployed by the TMV-Members repo's `hosting:web` target
// (scripts/build-web.sh assembles this dist/ + the /account and /waiver
// surfaces). Staging URL: https://themonkeyvault.web.app; the custom domain
// themonkeyvault.com attaches at DNS cutover — `site` already points there so
// canonicals/OG/sitemap are correct from day one (and staging pages canonical
// to the real domain instead of getting indexed).
//
// No `base`: the site serves from the domain root. (The old GitHub Pages
// deploy needed base '/TMV-Web'; Pages is retired — clean break.)
// Sitemap is generated by src/pages/sitemap.xml.ts (no external integration).
export default defineConfig({
  site: 'https://themonkeyvault.com',
  trailingSlash: 'ignore',
  build: { format: 'directory' },
  // Dev-only overlay (never ships in `astro build`/production) — off because
  // it sits over the phone-width preview during mobile work.
  devToolbar: { enabled: false },
  // No Astro prefetch integration: it injects <link rel="prefetch">, which iOS
  // Safari ignores and which would double up on the fetch()-based cache warmer
  // in BaseLayout. The warmer is the single owner of cache warming — it works
  // cross-browser and warms every on-screen internal link on idle, so a tap is
  // a 0-byte browser navigation that paints immediately.
});
