// @ts-check
import { defineConfig } from 'astro/config';

// Production host: Firebase Hosting (site `themonkeyvault` in project
// tmv-management), deployed by the TMV-Members repo's `hosting:web` target
// (scripts/build-web.sh assembles this dist/ + the /account and /waiver
// surfaces). Staging URL: https://themonkeyvault.web.app; the custom domain
// themonkeyvault.com attaches at DNS cutover — `site` already points there so
// canonicals/OG/sitemap are correct from day one (and staging pages canonical
// to the real domain instead of getting indexed).
//
// No `base`: the site serves from the domain root. (The old GitHub Pages
// deploy needed base '/TMV-Web'; Pages is retired — clean break.)
// Sitemap is generated by src/pages/sitemap.xml.ts (no external integration).
export default defineConfig({
  site: 'https://themonkeyvault.com',
  // Trailing slashes everywhere, matching directory hosting. Firebase serves
  // `/route/` as 200 and 301-redirects `/route` to it; emitting the slashed
  // form (see url() in src/data/site.ts) keeps every internal link redirect-free
  // so Astro's client router does a clean swap instead of falling back to a full
  // page load. 'always' makes Astro's own canonical + sitemap URLs match.
  trailingSlash: 'always',
  build: { format: 'directory' },
  // Dev-only overlay (never ships in `astro build`/production) — off because
  // it sits over the phone-width preview during mobile work.
  devToolbar: { enabled: false },
  // Every internal link is prefetched as soon as it scrolls into view, so by
  // the time it's tapped the target HTML is already cached and the swap is
  // instant. The previous 'hover' default never fired on touch devices — a tap
  // then had to fetch the page on click, which is the delay between clicking a
  // link and the page appearing. 'viewport' is the right default for a small
  // static site: pages are tiny HTML on a CDN, and it makes taps feel instant.
  prefetch: { prefetchAll: true, defaultStrategy: 'viewport' },
});
